### PR TITLE
fixed process exiting early

### LINKED ISSUE #2: Data is not loaded
# This is a Bug Report 

## Description
When running sls fixtures, data is not loaded, but sls deploy works. My guess is main process exits before  loading process is finished

### PR DESCRIPTION
**Pull request by jmaleonard**
## What did you implement:
Fixed process exiting early as promises are not resolved.
Closes #2 

## How did you implement it:
Resolving promises as the array that is returned does not resolve

## How can we verify it:

Call it

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by chechu** [comment]
Thank you for your PR! I'm sorry but I cannot see the differences. In both cases (your code and my code) the return value is the result of `Promise.all` with the array of promises...

**Comment by skrosoft** [comment]
I don't know if what I'm saying is right but it seems you was using an array of array using `push `you was adding an array to this array `const promises = [];`

Maybe you should use `concat()` instead of `push()`:
https://codeburst.io/jsnoob-push-vs-concat-basics-and-performance-comparison-7a4b55242fa9

**Comment by skrosoft** [comment]
@chechu @jmaleonard

I made a test using `concat()` instead of `push()` and it seems to work.

**Comment by jmaleonard** [comment]
In your initial one the implementation of tiny async pool has changed. Instead of resolving when you call it it simply pushes onto the array, but the return does not wait to resolve the promises hence an empty array. So by calling the promise.all earlier it fixes that issue.

**Comment by skrosoft** [comment]
> @chechu @jmaleonard
> 
> I made a test using `concat()` instead of `push()` and it seems to be working.

I was wrong. The @jmaleonard soluction's is working perfectly.

@chechu, could you please accept the @jmaleonard push request and tag a new version for NPM? Pleeeaaase :)

**Comment by chechu** [comment]
Merged, and pushing an update of package.json to generate a new release. Thank you for your support and patience :-) It's great to colaborate writing software :v:

**Pull request merged**
